sprint 16
muhammad-di/java-shareit pull request #4
Opened 2023-11-06 13:36 UTC by muhammad-di

2023-11-07 05:12 UTC, EugeneLenkevich requested changes
Привет! Спасибо за ПР

Вот это критичный момент :)

![image](https://github.com/muhammad-di/java-shareit/assets/109306643/860bac0d-56c9-47bd-a559-d04a469a3a41)

Лучше конечно у наставника уточнить что там не так, но на вскидку по логу похоже что что-то не так с docker-compose.yml, то есть с настройками

![image](https://github.com/muhammad-di/java-shareit/assets/109306643/d8bb9216-5a50-4c4b-beb3-422bfaa5f673)

предположу что их заполнить надо

![image](https://github.com/muhammad-di/java-shareit/assets/109306643/e47f5d56-c5c4-4e74-b08e-457653108d5a)

Привет, спасибо за ПР!

Вот этот момент критичен :)
![image](https://github.com/muhammad-di/java-shareit/assets/109306643/c4917fdd-5b41-46e0-b942-4cdd758b45eb)

Лучше, конечно, у наставника уточнить, не беглым взглядом предположу что проблема с docker-compose.yml, видимо не заполнены все нужные настройки  

![image](https://github.com/muhammad-di/java-shareit/assets/109306643/dc931edd-8d99-4307-97f7-c922f13800df)

![image](https://github.com/muhammad-di/java-shareit/assets/109306643/77d6593f-04b4-4631-b7a4-699e0a4e430c)

Насколько понимаю он должен примерно так выглядеть
![image](https://github.com/muhammad-di/java-shareit/assets/109306643/aed6823f-0159-4d74-ada6-b37fc18644d2)

2023-11-07 13:31 UTC, muhammad-di commented
Привет, Евгений! Спасибо за ревью)
Постараюсь как можно быстрее все исправить)

2023-11-13 12:05 UTC, muhammad-di commented
ВСЁ ПОЛУЧИЛОСЬ))))

2023-11-13 12:22 UTC, EugeneLenkevich approved these changes
Отлично, супер! :)
Это как раз те трудности что делают нас сильнее)

2023-11-13 12:27 UTC, merged